ERROR 2015-03-03 17:00:20,884 base Internal Server Error: /
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 89, in process_response
    new_response = panel.process_response(request, response)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/panels/staticfiles.py", line 129, in process_response
    'staticfiles_finders': self.get_staticfiles_finders(),
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/panels/staticfiles.py", line 140, in get_staticfiles_finders
    for path, finder_storage in finder.list([]):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 111, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py", line 27, in get_files
    directories, files = storage.listdir(location)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/files/storage.py", line 270, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/home/sturgelose/Git/bazaar/apps/bazaar/static'
ERROR 2015-03-03 17:01:47,517 base Internal Server Error: /
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 124, in process_response
    bits[-2] += toolbar.render_toolbar()
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 71, in render_toolbar
    return render_to_string('debug_toolbar/base.html', context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/template_timings_panel/panels/TemplateTimings.py", line 137, in timing_hook
    result = func(self, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
    six.reraise(*exc_info)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 547, in reverse
    key)
NoReverseMatch: u'djdt' is not a registered namespace
ERROR 2015-03-03 17:03:38,808 base Internal Server Error: /
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 124, in process_response
    bits[-2] += toolbar.render_toolbar()
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 71, in render_toolbar
    return render_to_string('debug_toolbar/base.html', context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/template_timings_panel/panels/TemplateTimings.py", line 137, in timing_hook
    result = func(self, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
    six.reraise(*exc_info)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 547, in reverse
    key)
NoReverseMatch: u'djdt' is not a registered namespace
ERROR 2015-03-03 17:04:52,175 base Internal Server Error: /
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 124, in process_response
    bits[-2] += toolbar.render_toolbar()
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 71, in render_toolbar
    return render_to_string('debug_toolbar/base.html', context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
    six.reraise(*exc_info)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 547, in reverse
    key)
NoReverseMatch: u'djdt' is not a registered namespace
ERROR 2015-03-03 17:08:03,126 base Internal Server Error: /
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 124, in process_response
    bits[-2] += toolbar.render_toolbar()
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 71, in render_toolbar
    return render_to_string('debug_toolbar/base.html', context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
    six.reraise(*exc_info)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 444, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 547, in reverse
    key)
NoReverseMatch: u'djdt' is not a registered namespace
ERROR 2015-03-06 17:18:48,080 base Internal Server Error: /
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/template_timings_panel/panels/TemplateTimings.py", line 137, in timing_hook
    result = func(self, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/template_timings_panel/panels/TemplateTimings.py", line 137, in timing_hook
    result = func(self, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/template_timings_panel/panels/TemplateTimings.py", line 137, in timing_hook
    result = func(self, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 102, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 81, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/cache.py", line 94, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/base.py", line 172, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/base.py", line 166, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/css.py", line 23, in split_contents
    filename = self.get_filename(basename)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/compressor/base.py", line 137, in get_filename
    self.finders and " or with staticfiles." or "."))
UncompressableFileError: 'shop/css/info.css' could not be found in the COMPRESS_ROOT '/home/sturgelose/Git/bazaar/public/static' or with staticfiles.
ERROR 2015-03-06 19:47:33,951 base Internal Server Error: /en-gb/accounts/login/
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sturgelose/Git/bazaar/apps/contrib/customer/views.py", line 98, in get
    self.request.session.pop(settings.LOGOUT_SESSION_KEY, None)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'LOGOUT_SESSION_KEY'
ERROR 2015-03-06 19:58:41,094 base Internal Server Error: /en-gb/accounts/login/
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sturgelose/Git/bazaar/apps/contrib/customer/views.py", line 99, in get
    self.request.session.pop(settings.LOGOUT_SESSION_KEY, None)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'LOGOUT_SESSION_KEY'
ERROR 2015-03-06 20:00:28,472 base Internal Server Error: /en-gb/accounts/login/
Traceback (most recent call last):
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sturgelose/Git/bazaar/apps/contrib/customer/views.py", line 99, in get
    self.request.session.pop(settings.LOGOUT_SESSION_KEY, None)
  File "/home/sturgelose/Git/oscar/local/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'LOGOUT_SESSION_KEY'
